// Date: 18.03.2016 1:26:24
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ru.winside.testmod.models;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class MagicStick extends ModelBase {
	public ModelRenderer Shape1;
	public ModelRenderer Shape2;
	public ModelRenderer Shape3;

	public MagicStick() {
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new ModelRenderer(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 2, 24, 2);
		Shape1.setRotationPoint(0F, -5F, 0F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 9, 0);
		Shape2.addBox(-1.5F, 0F, -1.5F, 3, 3, 3);
		Shape2.setRotationPoint(1F, -5F, 1F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		setRotation(Shape2, 0F, 0F, 0F);
		Shape3 = new ModelRenderer(this, 9, 0);
		Shape3.addBox(-1.5F, 0F, -1.5F, 3, 3, 3);
		Shape3.setRotationPoint(1F, -5F, 1F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		setRotation(Shape3, 0F, 0.7853982F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		float angle = 0.0f;
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Shape1.render(f5);
		GL11.glPushMatrix();
		GL11.glRotatef(angle++, 0f, 1f, 0f);
		GL11.glTranslatef(0, 0, 0);
		Shape2.render(f5);
		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glRotatef(angle++, 0f, 1f, 0f);
		Shape3.render(f5);
		GL11.glPopMatrix();
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
		//super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
		this.Shape2.rotateAngleY = MathHelper.cos(par7Entity.ticksExisted * 0.6662F + (float)Math.PI) * 1.4F * par2;
	}

}
